// SMSManagerMbmHeaders.h
// Generated by BitmapCompiler
// Copyright (c) 1998-2001 Symbian Ltd.  All rights reserved.
//

enum TMbmSmsmanagermbmheaders
	{
	EMbmSmsmanagermbmheadersCheck_on,
	EMbmSmsmanagermbmheadersCheck_on_mask,
	EMbmSmsmanagermbmheadersCheck_off,
	EMbmSmsmanagermbmheadersCheck_off_mask
	};
